# This solution is generated by claude code
# It takes 1m40s on my machine, even though it is parallelized and the Python solution takes 2s
use std


def find-invalid-id [number_str: string] {
    let length = $number_str | str length

    # Single digit numbers can't be invalid
    if $length < 2 {
        return null
    }

    # Try all possible partition sizes from 2 to length
    let results = (2..$length
        | each { |parts|
            # Only consider if length divides evenly by parts
            if ($length mod $parts) == 0 {
                let piece_size = ($length / $parts | into int)

                # Split number into pieces using chunks
                let pieces = ($number_str
                    | split chars
                    | chunks $piece_size
                    | each { $in | str join }
                    | uniq)

                # If all pieces are identical, return the number
                if ($pieces | length) == 1 {
                    $number_str | into int
                } else {
                    null
                }
            } else {
                null
            }
        }
        | compact)

    if ($results | is-empty) {
        null
    } else {
        $results | first
    }
}


def solve [] {
    $in
        | str trim
        | split row ","
        | par-each { |range|
            let parts = $range | split row "-"
            let lower = $parts.0 | into int
            let upper = $parts.1 | into int

            # Generate all numbers in range and check each
            $lower..$upper
                | reduce --fold 0 { |number, acc|
                    let number_str = $number | into string
                    let invalid_id = find-invalid-id $number_str
                    if $invalid_id == null {
                        $acc
                    } else {
                        $acc + $invalid_id
                    }
                }
        }
        | math sum
}

let result = open day-02/example.txt | solve
std assert equal $result 4174379265

open day-02/input.txt | solve
